FROM python:3.6

USER root
RUN set -x && \
    apt-get update
ENV HOME=/home

#USER root
WORKDIR $HOME
COPY ./environment.yml /$HOME/
COPY ./build_env.sh /$HOME/
COPY ./../results /$HOME/
COPY ./../src /$HOME/
RUN sh build_env.sh
CMD ["python", "src/deployment/app.py"]